name: Build and Release Nightly

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - name: Build executable for release
        run: swift build -v -c release -Xswiftc -disable-round-trip-debug-types
      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
      - name: Compress archive
        run: tar -czf chat.swift.nightly.${{ steps.timestamp.outputs.timestamp }}.tar.gz .build/release/chat.swift
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.ref_name }}-${{ steps.timestamp.outputs.timestamp }}
          files: chat.swift.nightly.${{ steps.timestamp.outputs.timestamp }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
